language: node_js
node_js:
- '6'
cache: yarn
branches:
  only:
  - ng-cli
  - dev
notifications:
  slack:
    secure_desc: itranga:[SLACK-TOKEN]
    secure: nln5Ls+wDh2URxdSOoe3aRq/Q8X0tPum6Vo16hGhqEojQUhiEJ0jvYBhCR7lv5fxCCFEQ6QWwp0fYrUCAOC9n2Nrqg3QQDHTuzAktissPCVu1NSZ7ULbJoyQnfnuiWTCvOtrKqYZK3gYQ5wgUPpfbyK4WelmjLFcvzO/3O22dAHmYImUfhS/GZUaJsJhAvEpAeg8ao/ygy/G5zn6keDb4j5l3STYi2YbY4mcGAliIKUlIJGWR6A+GhvpjStXu1BePg9ilzMxHxR0/I3hVn+MkQupmnITqCf6YunfwfF2bz4We21OfLfFURUImb49VR1FCDcF2wL1MV067R5O7aItWTPib9KMJDk28cQ8lJeGBFi/ZzkGLorXDfj9/ECZCGZuLse2/T21aail0VkepQN1j2luIsf48PFPx6O/WNh2dhKKdElImrfqPC47MHQ2mTlsGNqDj49mPDzS3cPhIZCaZC+uus55+LgVLnpht4W2JsMNNCc34SIgJ6P463WVg++4E6QzUBttJQCfEC8R0LLKhaqhsNkvmdBEQ8y+lt+rY/jtPBWPWv+TEwxqJQJ4jpkNiE8YZ40QW4N6FBxy60fq02n+m/ImHN9/5Lc0YtS5TkRVHeHnxG+kt1l0iyrkstMvb9CU8mwsf3LWZMZAoSnZAjubpqDJ8degP5XgdeGeDoM=
env:
  global:
  - PUSH_GIT_REPO: github.com/cavairexpert/caviarexpert.github.io.git
  - PUSH_GIT_BRANCH: master
  - secure_desc: GH_TOKEN=[TOKEN]
  - secure: Pb5RRgTS7lcWkXNMCBJlxPt31Nu1DPwu51xxItic+ZvHVuBglciTYe3SohoQ/9xo9VCgsZRiIoRxTMOsqJ2GQSHkrvQE3vVAffb8PvQAnVlsVuD+OLKZIv4rSuJiZ9NyoR3cTXs6dUYKJZnflL+zMM8K40+vVrpMRG95K8IJxnzhFJSdNSLgPCVfb1pRnbycSIWQyL6lCozz8oKa7z6ZJftIhAarSwZku8mEFgLZDc+ygfO+ltYqLbfJAee+8vDtmnUHKKusOZDhhBWARGcf9dV9TrSA+MXRuZhZ1WDdcrLuhUd8joAg1p/2J+WpTGAtdi2RfBBtPtVk0qwJhhqt5TSurS00PjmnAWrX+Y7jLfbr3wGgzzRZPwd/RJyxRCR06P2TNGaauJu/kILdaIKw/YCTbBkgpETJLk6nQPRNQ+BGHuJLNCP+9mkjIk2WCHNPHJgzI+qTjHBOrUgVmav114jTM4vyJDVDgE7P+xaCJi8QOeKA4V0KW6dYRFDfGNmpVcZcQQAy9upK9RxMN1k8W8t9y1fAyiM4aAw7r3SUup42YCtXLFFURo0K+ZjfFWv7HRFHyJ9jySBQGG7/8ZmEw5tSXy1AgypT8RPQDPlU8cafYg/pM9aa4mfOXa94QXTkV22QNL049EpT1B7cIOOvI9M/+8TQB77kgVqTzPP9BB4=
before_install:
- cat /dev/null > .yarnrc
- curl -fSL "https://releases.hashicorp.com/terraform/0.10.2/terraform_0.10.2_linux_amd64.zip"
  -o terraform.zip
- sudo unzip terraform.zip -d /opt/terraform
- sudo ln -s /opt/terraform/terraform /usr/bin/terraform
- rm -f terraform.zip
script: yarn run build
before_deploy:
- cat /dev/null > .gitignore
- cp ./deploy/404.html ./dist
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "./dist"
  on:
    branch: ng-cli
  target_branch: master
  github_token: $GH_TOKEN
