language: node_js
node_js:
- node
cache: yarn
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: JCGHdrGQzxei0hgWKc3hXruxn21OK070GkYLYLQpGl47yaIUP5QZWVZ5TlkxrqF+UE7qjCDeTI9p6ljA86yVvFNXG1Y2iK4MlmlOAt7+9l3NXQxnpci+8/1uEnvem37pXaez2VkC9WurXCnetUZ7nFxJo2QwaOIeV9K/dRVISh+VzScUgxMq0aJZjrvr++kORwO1sxfgWXYaKt5cWzlKPP6PFlJco9P40Th+eb3mOu4x3C6VpZn6ApvSwBMNXZIwnLHOVnmQwFEdRCAF1GcwZHLteRwHnHOshIMJdlZXLOYFyDoL8YXFeKeBLiIN0oqODf5KKsMHI1nj5Jjlh0shMsUihCI/bAapPd/4051f28brblgxD8/+y9/7dUT10PzhXPWTqMTOWAePRDlvNvfBYbCNXeYlgXP+jZ6WjiJF8aC18Kr+qRL2n6914Tsi/JqG+I/3iXmnfwSt7fx1FUOj7KAwaZ4bNqL0wY08hQpgrRvQ8QjJK4GxdXlcJCdCiPQSWJL3hW4KW7MOqbFEhtWv9WTGzGveniG6NcKt2itBBPRHgLzCeAxah2u69i8Tpv10xs/sr79V/NvSJnEBv+Ta2uxOd++Dur7RN5U9Ypyk6jdJE2bFXZgJkLjA3xTdx8muiWCea3eQFYhWXHfkgUl109KYeaCgLsDqfDJl/2Bcbp4=
  on:
    branch: master
branches:
  except:
  - master
notifications:
  slack:
    secure_desc: itranga:[SLACK-TOKEN]
    secure: nln5Ls+wDh2URxdSOoe3aRq/Q8X0tPum6Vo16hGhqEojQUhiEJ0jvYBhCR7lv5fxCCFEQ6QWwp0fYrUCAOC9n2Nrqg3QQDHTuzAktissPCVu1NSZ7ULbJoyQnfnuiWTCvOtrKqYZK3gYQ5wgUPpfbyK4WelmjLFcvzO/3O22dAHmYImUfhS/GZUaJsJhAvEpAeg8ao/ygy/G5zn6keDb4j5l3STYi2YbY4mcGAliIKUlIJGWR6A+GhvpjStXu1BePg9ilzMxHxR0/I3hVn+MkQupmnITqCf6YunfwfF2bz4We21OfLfFURUImb49VR1FCDcF2wL1MV067R5O7aItWTPib9KMJDk28cQ8lJeGBFi/ZzkGLorXDfj9/ECZCGZuLse2/T21aail0VkepQN1j2luIsf48PFPx6O/WNh2dhKKdElImrfqPC47MHQ2mTlsGNqDj49mPDzS3cPhIZCaZC+uus55+LgVLnpht4W2JsMNNCc34SIgJ6P463WVg++4E6QzUBttJQCfEC8R0LLKhaqhsNkvmdBEQ8y+lt+rY/jtPBWPWv+TEwxqJQJ4jpkNiE8YZ40QW4N6FBxy60fq02n+m/ImHN9/5Lc0YtS5TkRVHeHnxG+kt1l0iyrkstMvb9CU8mwsf3LWZMZAoSnZAjubpqDJ8degP5XgdeGeDoM=
env:
  global:
  - PUSH_GIT_REPO: github.com/cavairexpert/caviarexpert.github.io.git
  - PUSH_GIT_BRANCH: master
  - secure_desc: GH_TOKEN=[TOKEN]
  - secure: yWL8DMPrNyKS5jKwfjKWPSrZ3USOkK5xzNNyuVEGoYkqcgEo+RdwrfwmgksvG9dlktq3lkLqPckEPZOc4KwlkU/p/F8j+MKiszm4yXhebnJI5nEjDm9p0Dqx015M2fKalNxQfI8Mf0XyVKb6N7O+Gt6g7FCuviQAatDtNhRjw7RW8pLzgd5SbHshuBrM1qzWzBbQarwcFRvDHb2X4/4RHpEqX0ApSlyFvHWqvQVvcJya6uMU2hRePTcaplAgpYfKrM9Wk19m9VKhswxoApP91cEgMNAuHIQyTuZue714DYoG9T3FrGAexZ08SQUZNJ65WWOYBTcmXmJKN2lbzUHVAhE4jSpykC5HclZuTmUN7W5ukKQRmorK/JiMQrd8nA9BDbtpfdU6IqaK71WOqnJQ9zPDUOLJFRHKVNN7E6+SfT2fgxAunpfx/kc/3yTm25kQyLQduHVgjvbpmGw9GqrjFQYIpqqr3DbwYtY2u05FUWgqa/0e8AWB2DOq/oH53tTrqMo0m//ZMNyQEh83sf3yXEnQuWdI0oQbck9weSm/aAoP5crSXlp7WjvNGbnyJ/TmjAEfAxj3LIfndbaUvIzGCP4s2swwXoS+UnfedXGU/5V2POYyQpdycjFIYg5RPIL9xF9djNxxJBddHCGdN3vFAGaoI3Iu9G4DBxhw8UZAtNk=
