language: node_js
node_js:
- '6'
cache: yarn
branches:
  only:
  - ng-cli
  - dev
notifications:
  slack:
    secure_desc: itranga:[SLACK-TOKEN]
    secure: nln5Ls+wDh2URxdSOoe3aRq/Q8X0tPum6Vo16hGhqEojQUhiEJ0jvYBhCR7lv5fxCCFEQ6QWwp0fYrUCAOC9n2Nrqg3QQDHTuzAktissPCVu1NSZ7ULbJoyQnfnuiWTCvOtrKqYZK3gYQ5wgUPpfbyK4WelmjLFcvzO/3O22dAHmYImUfhS/GZUaJsJhAvEpAeg8ao/ygy/G5zn6keDb4j5l3STYi2YbY4mcGAliIKUlIJGWR6A+GhvpjStXu1BePg9ilzMxHxR0/I3hVn+MkQupmnITqCf6YunfwfF2bz4We21OfLfFURUImb49VR1FCDcF2wL1MV067R5O7aItWTPib9KMJDk28cQ8lJeGBFi/ZzkGLorXDfj9/ECZCGZuLse2/T21aail0VkepQN1j2luIsf48PFPx6O/WNh2dhKKdElImrfqPC47MHQ2mTlsGNqDj49mPDzS3cPhIZCaZC+uus55+LgVLnpht4W2JsMNNCc34SIgJ6P463WVg++4E6QzUBttJQCfEC8R0LLKhaqhsNkvmdBEQ8y+lt+rY/jtPBWPWv+TEwxqJQJ4jpkNiE8YZ40QW4N6FBxy60fq02n+m/ImHN9/5Lc0YtS5TkRVHeHnxG+kt1l0iyrkstMvb9CU8mwsf3LWZMZAoSnZAjubpqDJ8degP5XgdeGeDoM=
env:
  global:
  - PUSH_GIT_REPO: github.com/cavairexpert/caviarexpert.github.io.git
  - PUSH_GIT_BRANCH: master
  - secure_desc: GH_TOKEN=[TOKEN]
  - secure: Xuowb228LWj9Xa7HPQvwleDWqREzFSnViivZGZ1JjjLGljhEf5OTPtCCsGA1H9x3SVo+MVM6qAyNA53gR40bub5uKBVSnqkQA+9ZB41wjry8tIQo4M1rHFr3UywrXlmujVActspY7OD5zXmkuwb3BBZBYNgYgI/ZotFJBlu0G7W96ZxuQ28bEIuYEqCeIsZ2BJoELXYoCdiRvJgFkFoqIDNvAZYjcUSY/zFzveqZm9vNrUtCQBhve1fYu6tQQEkPwoO01a+CZwb/8Hh8T06KAns8ClHqYGzF1ySWqCfcAl07+D7WsYOm9v9BhyA2lbArfBRKT6ox4YLllw22n8ATYPiFgKAIwAIUC2BF/63sZYLaVIK1uSf6Vg5eyop8LhpiOSIIis4FvZrmvJmZ0m0Hx3UhLL36dTJNymmpxDb3g0zA93obAMut5iolzQ0ueFDsOGpI84Oj4W+ukJWyO0k+8GULkjcCNCFyranhqUmawibYubXaLL+IUI86nbYuTbbAUSC6ABG4348t9k7/YoHnB4IqujRsXtvVACLAYoc4fH9PgUdKmeN+P76sXtBJ1YELzTDEpUPsrMM70Mn1xEDYzhadJHwJ2ROoqoCRsVJu59ja9pDLtNTeby1kVBflO/HuSBtynAsOoAZBArgkygOnYGvmotoTIfcLNVht6HhWQ40=
before_install:
- cat /dev/null > .yarnrc
- curl -fSL "https://releases.hashicorp.com/terraform/0.10.2/terraform_0.10.2_linux_amd64.zip" -o terraform.zip
- sudo unzip terraform.zip -d /opt/terraform
- sudo ln -s /opt/terraform/terraform /usr/bin/terraform
- rm -f terraform.zip
script: yarn run build
before_deploy:
- cat /dev/null > .gitignore
- cp ./deploy/404.html ./dist
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "./dist"
  on:
    branch: ng-cli
  target_branch: master
  github_token:
    secure: cIsHnjOO3drSqPEQLXJVGqAjbkjTzU5vRKKmx2dt1GeupfwN4x07vuGTz2omC6GkSmIOEkU9gU8fNqXs3VSpirzpQKwCxUz4XPOQmB9afxvwDidGWqMK0yZCz5CIEiiuMtRxxD+DBZHQ1ILqXO2/lpEOPWbpr6/4ZsgtcQIZzZgpXGopepmkRaGD+XO1zR2lxF4IZNlADux5adtURBO+A2qBkPv+D4dBnhNnCrWK8AoWcmQq5QH4tBQ+3tsQl+k4MBgAOQaBZ09jYvkO9tHFdaIi8YXb0eMio/IL3910WZ4yBwzPfQ6FpNV00alVBSj6bafghVX0sII4zdgCksnUuL1Qi87Ojws3nl2tvrR9WM8QMGJkIQsOQCM07aG+mxg1wX7wQnBq2Srw9V21xvNYajLQcxu53GRewDJa+6bbCHjiT4+X+Tz/oIQ19WcyuxwVy2jLzgOM4JShMUtztMWsPKkjYSZRWhWmp6GBwnF7Xo6dkpH1CnrTDWvoQxfRCfFCKJMEUeyr8gnq16oL+LyQcG7S65iHq/HwNBUskacgL1OFS80sQ98RvFRpPlLSwm8UW4XMl9FwV4ThShUwpmqh1ld5PVKelJiWXnzZr1LrYlwgbswV5bkxxi38v4mcot//mmCHccGE9HrgoZ9jBg8vZLurazDp2TjyZHyqaqne6OE=
